server:
  port: 18080
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
#spring:
#  profiles:
#    active: dev
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.107:3306/school?characterEncoding=utf-8&&nullCatalogMeansCurrent=true&&serverTimezone=GMT
#    username: root
#    password: root
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5


#---
#server:
#  port: 18082
#spring:
#  profiles: dev
